- name: Add EC2 host dynamically
  hosts: localhost
  tasks:
    - name: Add EC2 host from Terraform
      add_host:
        name: "{{ lookup('pipe', 'terraform output -raw instance_ip') }}"
        groups: ec2
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /keys/sshkey.pem
        ansible_python_interpreter: /usr/bin/python3

- name: Install and test Nginx
  hosts: ec2
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install curl
      yum:
        name: curl
        state: present

    - name: Test Nginx
      shell: curl -s http://localhost
      register: nginx_page

    - name: Show Nginx content
      debug:
        msg: "{{ nginx_page.stdout }}"
